# Generated by Django 4.0.2 on 2022-03-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_pocket_bank_account_and_more'),
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='cycle',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
