# Generated by Django 4.0.2 on 2022-03-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_initial'),
        ('cycles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.account'),
        ),
    ]
