# Generated by Django 4.0.2 on 2022-03-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_pocket_bank_account_pocket_vault'),
        ('cycles', '0004_income_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('in_outside_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('in_outside_notes', models.CharField(blank=True, max_length=160, null=True)),
                ('out', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('out_notes', models.CharField(blank=True, max_length=160, null=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycles.cycle')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.pocket')),
            ],
        ),
    ]
