# Generated by Django 4.0.2 on 2022-03-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0006_incomelendingslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='incomedistributor',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='incomedistributor',
            name='pocket',
        ),
        migrations.RemoveField(
            model_name='incomelendingslip',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='incomelendingslip',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeDistributor',
        ),
        migrations.DeleteModel(
            name='IncomeLendingSlip',
        ),
    ]
