# Generated by Django 4.0.2 on 2022-03-17 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0007_initial'),
        ('cycles', '0007_remove_income_bank_account_remove_income_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('in_outside_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('in_outside_notes', models.CharField(blank=True, max_length=160, null=True)),
                ('out', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('out_notes', models.CharField(blank=True, max_length=160, null=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycles.cycle')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.pocket')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeLendingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='cycles.incomedistributor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='cycles.incomedistributor')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.account')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.cycle')),
            ],
        ),
    ]
