# Generated by Django 4.0.2 on 2022-04-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='cash',
            new_name='is_cash',
        ),
    ]
