# Generated by Django 4.0.2 on 2022-04-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0010_rename_bank_account_income_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='is_cash',
        ),
    ]
