# Generated by Django 4.0.2 on 2022-04-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0011_remove_income_is_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='cycles.cycle'),
        ),
    ]
