# Generated by Django 4.0.2 on 2022-04-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0013_cycle_timespan_alter_cycle_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedistributor',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.cycle'),
        ),
        migrations.AlterField(
            model_name='incomedistributor',
            name='money_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incomedistributor',
            name='out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
