# Generated by Django 4.0.2 on 2022-04-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_rename_bank_account_pocket_account'),
        ('cycles', '0014_alter_incomedistributor_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedistributor',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='cycles.cycle'),
        ),
        migrations.AlterField(
            model_name='incomedistributor',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='goals.pocket'),
        ),
    ]
