# Generated by Django 4.0.2 on 2022-03-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('percent_of_net', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('percent_locked', models.BooleanField(default=False)),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('money_in_locked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='PocketGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=320)),
                ('percent_of_goal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('percent_locked', models.BooleanField(default=False)),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('money_in_locked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=320)),
                ('percent_of_wallet', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('percent_locked', models.BooleanField(default=False)),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('money_in_locked', models.BooleanField(default=False)),
                ('in_outside_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('in_outside_notes', models.CharField(blank=True, max_length=160, null=True)),
                ('out', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('out_notes', models.CharField(blank=True, max_length=160, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.account')),
                ('pocket_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.pocketgroup')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.vault')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.wallet')),
            ],
        ),
    ]
