# Generated by Django 4.0.2 on 2022-03-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='pocket_group',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='vault',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Pocket',
        ),
        migrations.DeleteModel(
            name='PocketGroup',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
