# Generated by Django 4.0.2 on 2022-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goal_options_alter_pocket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='description',
            field=models.TextField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, max_length=320, null=True),
        ),
    ]
