# Generated by Django 4.0.2 on 2022-04-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_goal_description_alter_pocket_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='pocket_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pockets', to='goals.pocketgroup'),
        ),
    ]
