# Generated by Django 4.0.2 on 2022-03-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_remove_income_bank_account_remove_income_cycle_and_more'),
        ('goals', '0002_remove_pocket_bank_account_and_more'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Vault',
        ),
    ]
