# Generated by Django 4.0.2 on 2022-03-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_remove_lendingslip_receiver_and_more'),
        ('cycles', '0007_remove_income_bank_account_remove_income_cycle_and_more'),
        ('banks', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Vault',
        ),
    ]
