# Generated by Django 4.0.2 on 2022-04-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vault',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='banks.bank'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='banks.account'),
        ),
    ]
